version: '3.6'

# Database Services ----------------------------------
services:

  db:
    image: mariadb:10.1
    container_name: mariadb
    restart: always
    volumes:
      - ./mysql/initdb/:/docker-entrypoint-initdb.d
      - ./mysql/data/:/var/lib/mysql
      # - ./mysql/my.cnf:/etc/my.cnf
    environment:
      - MYSQL_ROOT_PASSWORD=root
      # - MYSQL_DATABASE=db_name
      # - MYSQL_USER=db_usr
      # - MYSQL_PASSWORD=db_password
    ports:
      - "3306:3306"

  pma:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - "8000:80"

  redis:
    image: redis:latest
    container_name: redis
    restart: always

  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - 8081:8081

networks:
  default:
    external:
      name: lemp-network
# ------------------------------------------------------
